### ISSUE TITLE
Hackage release?

### ISSUE THREAD

**Issue by ali-abrar** [netrium/Netrium#3]
Is there any interest in releasing this package on hackage? If there are hurdles, I'd be interested in helping overcome them.

**Comment by eleventy7** [comment]
Hi @ali-abrar,

Please go ahead, assuming you keep the license etc in place. Many thanks for your effort in keeping netrium up-to-date - it has been some time since we've actively looked at it.

Best,
Shaun

**Comment by ali-abrar** [comment]
Thanks, Shaun. I'll have a few minor changes to the cabal file before release, most likely. I'll put up a PR.

**Comment by ali-abrar** [comment]
As promised: https://github.com/netrium/Netrium/pull/4
